package asgn2Exceptions;
/**
 * This class represents any exceptions generated by the operation
 * of the train.  If you find something is wrong with the train then 
 * you should throw a new instance of this class.
 * 
 * @author Yiting Zhang  
 * @version 1.0
 */


public class TrainException extends Exception{

	/**
	 * Creates a new instance of TrainException.
	 * 
	 * @param message an informative message about the problem found
	 */
	public TrainException(String message) {
		super("Train Exception: " + message);
	}

}
